version: 1.2
workflows:
       -  name: foobar
          subclass: wdl
          primaryDescriptorPath: /Dockstore2.wdl
          testParameterFiles:
              - /dockstore.wdl.json
          latestTagAsDefault: false
          authors:
              - name: WDL man without orcid
                email: test@gmail.com
                role: Not spy
                affiliation: OICR
              - name: WDL man with orcid
                orcid: 00000-11111-00000
       -  name: foobar2
          subclass: cwl
          primaryDescriptorPath: /Dockstore.cwl
          latestTagAsDefault: true
          testParameterFiles:
              - /dockstore.cwl.json
          authors:
              - name: Man without orcid
                email: test@gmail.com
                role: Not spy
                affiliation: I spy2
              - name: Man with orcid
                orcid: 00000-22222-00000
